apiVersion: v1
kind: Secret
metadata:
  name: config
type: Opaque
data:
  db_password: ZmFzdGFwaQ==
  secret_key: ZmFzdGFwaQ==
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  db_database: fastapi
  db_user: fastapi