apiVersion: v1
kind: Service
metadata:
  name: fastapi
spec:
  type: NodePort
  selector:
    app: fastapi
    tier: app
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
spec:
  selector:
    matchLabels:
      app: fastapi
      tier: app
  template:
    metadata:
      labels:
        app: fastapi
        tier: app
    spec:
      containers:
      - name: fastapi
        image: sr_fastapi-fastapi
        imagePullPolicy: Never
        env:
          - name: DB_USER
            valueFrom:
              configMapKeyRef:
                name: config
                key: db_user
          - name: DB_DATABASE
            valueFrom:
              configMapKeyRef:
                name: config
                key: db_database
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: config
                key: db_password
          - name: DB_HOST
            value: db
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: config
                key: secret_key
        ports:
        - containerPort: 8000
          name: fastapi