name: sr_fastapi

services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    entrypoint: ["tail", "-f", "/dev/null"]
    ports:
      - "8000:8000"
    volumes:
      - ../src:/app
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PW: ${DB_PW}
    depends_on:
      - db
  db:
    image: postgres:16.10-bookworm
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PW}
