name: sr_fastapi
services:
  fastapi:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    environment:
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_USER: "${DB_USER}"
      DB_DATABASE: "${DB_DATABASE}"
      DB_HOST: db
    volumes:
      - ../src:/app
    depends_on:
      - db
  db:
    image: mariadb:10-6
    environment:
      MARIADB_ROOT_PASSWORD: "${DB_PASSWORD}"
      MARIADB_PASSWORD: "${DB_PASSWORD}"
      MARIADB_USER: "${DB_USER}"
      MARIADB_DATABASE: "${DB_DATABASE}"